Yc search filter
ddm1293/FurFinder pull request #42
Opened 2023-06-30 04:23 UTC by ddm1293

2023-07-01 03:05 UTC, SeePeaJay approved these changes

2023-07-01 03:40 UTC, Huiwen-Zuo requested changes
Works well on my pc,

2023-07-01 03:40 UTC, Huiwen-Zuo commented on frontend/src/components/CreateThread/CreateThreadPetInfo.js
From lines 28-35, I thought we'd agreed that the Name field is required for both lostPetThread and witnessThread? Lines 10-14 is the useEffect to prefix the petName on both types of threads. I don't think we need  "threadType === 'lostPetThread' &&" part and the previous version is working well.

2023-07-02 01:48 UTC, ddm1293 commented on frontend/src/components/CreateThread/CreateThreadPetInfo.js
i cannot see which lines you were referring to.

2023-07-02 04:20 UTC, Huiwen-Zuo commented on frontend/src/components/CreateThread/CreateThreadPetInfo.js
After discussion, I'll change this on my next version of FE. Ok to merge this.

2023-07-02 04:20 UTC, Huiwen-Zuo approved these changes

2023-07-02 04:20 UTC, merged